### ISSUE TITLE
랜딩 페이지 배포 일정 관련

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/global-summit-#1]
코드는 이미 어제 PR 날려서 matt이 받아주기만 하면 되는데 자나 봐요.
언제 리뷰하고 실서버에 적용할지 물어봤는데 아직 반응이 없어요
저녁 때 쯤 되면 뭐라고 얘기해 주겠죠?

이슈: creativecommons/global-summit-#23
땡기기 요청: creativecommons/global-summit-#24

**Comment by jenniferkang** [comment]
@mozodev 어제 션님께서 다시 메일을 보냈어요.  아직도 matt이 반응이 없나요?

**Comment by mozodev** [comment]
제 풀 리퀘스트도 아직 안 받았습니다. 받으면 메일이 오겠지만 그 코드를 서버에 적용도 해야해서 어쨌든 저는 다음 url만 확인하고 있습니다. https://summit.creativecommons.org/kr

**Comment by mozodev** [comment]
완료~
