### ISSUE TITLE
Slack 채널 오픈

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#10]

**Comment by soohyunpae** [comment]
cckorea 팀 슬랙 계정 있나요? 기존 계정이 있으면 그 아래에 써밋 채널 추가로 열면 될 것 같아서요.

**Comment by soohyunpae** [comment]
CC Global Summit 2015 팀으로 만들었어요. 
주소는 https://ccgs2015.slack.com 입니다.
@mozodev @jenniferkang @nanshil 일단 세 분 초대해드렸어요~  저희끼리 한번 테스트해봐요.

**Comment by soohyunpae** [comment]
organisers private channel 만들었어요.
@nanshil @khseo  님 초대받으실 이메일 알려주세요~!

우리 이거 만들었다고 HQ 팀에도 공유하고, Steering Committee 에서도 써보자고 제안할까봐요.

**Comment by jenniferkang** [comment]
@mozodev  님 우리 슬랙  아이디 만들때요. 기냥 승훈이 아이디로 만들었던가요? 
음... 슬랙은 비영리단체는 후원해주고 이런거 없는지 함 살펴봐주실래요? 
@soohyunpae CC HQ는 이미 슬랙 사용하죠? 비영리단체들에게는 용량 제한같은거 풀어주고 그런거 없는지... 함 여쭤봐주세요.

**Comment by soohyunpae** [comment]
https://slack.zendesk.com/hc/en-us/articles/204368833-Slack-for-Nonprofits-program
보니까 미국 등록된 단체 아니면 관련 서류를 제출하라고 되어 있네요.

근데 비영리여도 100명까지 회원수 제한은 있고요.

 cckorea 아이디 있으면 그걸로 하는 게 좋을 거 같긴 해요. 없으시면 HQ에 전에 있던거 아직 유효한지 물어볼게요.

**Comment by mozodev** [comment]
작년에 만들었던 씨씨코리아 슬랙입니다.
https://cck.slack.com

Slack for Nonprofits program
https://slack.zendesk.com/hc/en-us/articles/204368833-Slack-for-Nonprofits-program
standard 플랜을 무료로 사용하게 해준다네요

![slack-pricing](https://cloud.githubusercontent.com/assets/1661950/8224755/f2fbcf1a-15c6-11e5-89b7-aa487cc1c927.png)
Upload your nonprofit certification
This is most likely a letter from the IRS showing your 501(c)(3) tax-exempt status or your local equivalent. Please include a scanned copy of this document.

**Comment by soohyunpae** [comment]
그럼 그 안에 새로 그룹 만드는 게 낫겠네요.

**Comment by jenniferkang** [comment]
네 새로 만드는게 좋을 것 같아요.

2015-05-29 12:29 GMT+09:00 Soohyun Pae notifications@github.com:

> cckorea 팀 슬랙 계정 있나요? 기존 계정이 있으면 그 아래에 써밋 채널 추가로 열면 될 것 같아서요.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommonskorea/global-summit-/issues/10#issuecomment-106671185
> .

## 

_강현숙  *Jennifer Kang_[image: cckorea_logo3.png]*

 CCKOREA | 사무국장

 _Twitter @hskang      Tel_ 070-7618-0321

 hskang211@gmail.com

_Address *_마포구 서교동 363-20 5층 \* (오시는길
http://map.naver.com/?dlevel=12&pinType=site&pinId=12231010&x=126.9218731&y=37.5511880&enc=b64
)

_Sites  CCKOREA_ (cc http://cckorea.org/korea.org http://cckorea.org/)*
공유허브 _(_sharehub.kr http://sharehub.kr/_)  *코드나무 *(_codenamu.org
http://codenamu.org/*)

**Comment by soohyunpae** [comment]
@mozodev 저 cck.slack.com에 초대 좀 해주세요 ㅎ

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 
http://cck.slack.com

경희님, 난실님, 희정님, 션님 초대했습니다.
메일 확인하시고 가입하시면 로그인할 수 있습니다.

#global-summit-2015 채널에서 글로벌 서밋!

**Comment by soohyunpae** [comment]
저는 어느 계정으로 초대해주셨어요? soohyun@creativecommons.org로 초대해주실 수 있으세요? 그냥 가입하려고 보니까 cckorea.org 계정이 있어야 하나봐요.

**Comment by mozodev** [comment]
@soohyunpae 지메일로 했는데 방금 HQ로 초대해드려서 채널에 잘 들어오신거 확인했습니다~

**Comment by soohyunpae** [comment]
@mozodev 네 감사합니당~ 기존에 제가 만든 슬랙은 삭제할게요.

**Comment by jenniferkang** [comment]
잠깐이요~~~
써밋 슬랙은 따로 만드는거죠?

2015CCsummit 뭐 이렇게. 맞죠?

2015-06-18 15:17 GMT+09:00 Soohyun Pae notifications@github.com:

**Comment by mozodev** [comment]
반대로 였는데요 션님이 따로 만든거 삭제하고 기존 CC코리아 계정에 채널을 만든거죠... #global-summit-2015

**Comment by jenniferkang** [comment]
션님~ 지우지 말고요. 써밋용으로 따로 만들어요.

2015-06-18 15:33 GMT+09:00 Yeongtaek Hong notifications@github.com:

**Comment by soohyunpae** [comment]
엣...아... 주최팀 슬랙 채널만 cck 슬랙에 만들자고 하신거였어요?ㅋ

이미 지웠는데.ㅠㅠ
다시 만들게요.ㅎ

**Comment by soohyunpae** [comment]
ccglobalsummit2015.slack.com

퍼블릭용 슬랙 오픈했습니다.
현재 @jenniferkang @mozodev 님 초대해드렸어요.
나머지 두분은 @nanshil @khseo 님은  nanshil 앳 cckorea.org / khseo 앳 cckorea.org 이리로 초대해드리면 될까요?

**Comment by mozodev** [comment]
@soohyunpae 난실님은 dalcomnews 쥐멜... 경희님은 맞아요~

**Comment by soohyunpae** [comment]
슬랙에 HQ 멤버들 중 써보겠다는 사람 우선 초대했어요. 며칠 우리끼리 써보고 affiliates 리스트에 오픈 할게요~
