### ISSUE TITLE
affiliate 설문조사

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#11]
재미있는 아이디어/이벤트 관련 설문조사 affiliate에게 뿌리기

**Comment by jenniferkang** [comment]
설문조사입니다.  함 검토해 주세요. 
https://docs.google.com/document/d/1DGpGilcLY5N6rOM-FM-d0TlqcAZOx_bLVbGgf4bU3DE/edit

**Comment by soohyunpae** [comment]
일단 번역해서 구글폼으로 만들어볼게요~

**Comment by soohyunpae** [comment]
구글 양식으로 만든 영문 버전입니다.
https://docs.google.com/forms/d/1_olT0znX0ZpCWd7M-pa8GoIW55W_YCer0fk3ALy_1Dg/edit?usp=sharing

추가하거나 수정할 부분은 기존 한글 버전에 추가해주시고 알려주세요~

**Comment by jenniferkang** [comment]
설문조사 결과 https://docs.google.com/spreadsheets/d/13eULO2cwCcZxhSenma0Xawq98Y38c3c1ic9kwWubuNI/edit#gid=120527113 

@soohyunpae : 설문조사 문항에 커뮤니케이션 툴 살짝 추가하는거~

**Comment by soohyunpae** [comment]
추가 완료했습니다~
