### ISSUE TITLE
호텔 가예약

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#14]
5월말까지 유효한 요율 재확인, standard 80개 예약.
예약 정책, 취소/환불/변경 관련 정책 확인 후 HQ에 공유.

**Comment by soohyunpae** [comment]
HQ에서 board는 인원수 체크 중

**Comment by jenniferkang** [comment]
@soohyunpae 님 호텔 답사후 정보 
https://docs.google.com/spreadsheets/d/1j4_B3NlArJ0MRp9lJ-D21jEsejqx-SDTEMeGJhTrjzc/edit#gid=0

최종 견적을 다시 받을 예정입니다.

**Comment by jenniferkang** [comment]
오늘 최종 견적이 왔는데.
명동 이비스쪽으로 잠정적으로 결정 
@nanshil님 명동 이비스측에 
- 정확한 위치 (주소) 
- 이비스 웰컴 파티 할 만한 장소 있는지 - 가격 무료로 해줄 수 있는지?
- 음료, 맥주같은거 그쪽에서 준비해줄 수 있는지 물론 유료로..  
- VIP용 룸 여부 
  함 확인해 봐주세요. 
  이건 시간 있으니 내일 이사회 끝나고 목요일에 출근하셔서 알아봐주세요.

**Comment by nanshil** [comment]
명동 이비스는 9월 오픈이랍니다. 다음주부터 답사 가능하다고 해서
우선 다음주 목요일로 일정 잡아달라고 이야기했어요! @서경희님 일정빼주세요~ 
- 주소는 정확히 다녀와서 접근성, 교통 확인할께요!
- 레스토랑은 확실히 있는데 다른 부대 시설은 확인해봐야한다고 해서 이것도 다음주에 다녀와서 공유할께요!
- 스위트룸이랑 있다고 하네요~

그래서 결론은...
다음주 다녀와서 명확하게 공유할께요!
우선 마포 시티는 다음주까지 홀딩으로 이야기하고 다녀와서 결정지을께요!

션님 일정 괜찮으신가요? @soohyunpae 

2015년 6월 2일 오후 8:19, jenniferkang notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
네 저도 일정 괜찮아요~ @khseo 님 태그 안걸려서 다시 걸어요. ㅎ

**Comment by khseo** [comment]
저도 일정 괜찮습니다 :))

**Comment by nanshil** [comment]
6월 11일(목)  오후 2시에 일정 잡았습니다.
주소는 "서울시 중구 북창동 93-52 북창동 M 호텔" 입니다.
시청역에서 가깝네요~
위치는 한번 가보고 인사동으로할지, 명동으로 할지 결정합시다!

2015-06-04 16:41 GMT+09:00 khseo notifications@github.com:

**Comment by khseo** [comment]
네~ CC캘린더에 일정 추가했습니다.

**Comment by nanshil** [comment]
![f-type 0](https://cloud.githubusercontent.com/assets/11845030/8225439/94ed4de6-15cf-11e5-8acd-cf694f94b640.JPG)
![f-type 2](https://cloud.githubusercontent.com/assets/11845030/8225440/94f1a030-15cf-11e5-83f8-c19dbcab1b48.JPG)
![type-a view-1 fin](https://cloud.githubusercontent.com/assets/11845030/8225441/94f2a1f6-15cf-11e5-9024-d9dba6e0973c.jpg)
- 마포롯데 시티 호텔에서 견적을 재조정해서 왔네요~
  일반실 165,000원(조식포함, 부가세포함) 입니다.
- 북창동쪽(moka호텔이라고 하네요)은 객실 사진 참고용으로 보내왔습니다.
  객실 크기는 다시 확인해봐야할 것 같고
  일반실은 112,200원으로 이야기 했습니다.

-> 여전히 5만원이 넘게 차이가 나서
북창동 호텔로
: 프리 오픈때 사용
: 스위트룸 가격 내고
: 옥상 또는 연회장(우천시) 무료 사용 조건으로 내일 이야기해보도록 할게요~~

​

2015-06-04 16:41 GMT+09:00 khseo notifications@github.com:

**Comment by soohyunpae** [comment]
@nanshil 님 아직 확정 안되셨죠?
모카 호텔 사진 받으시면 공유 부탁드릴게요~ HQ에도 아래 내용과 함께 전달하려고요.
- VIP도 다같이 묵도록 (일반실 112,200원, 스위트룸 가격 확인 필요)
- 신규 오픈이라 파격할인한 가격임
- 상황봐서 셔틀 운영 고려 중

**Comment by nanshil** [comment]
@soohyunpae 님~ 경희님이 전달해준 이비스 스타일 명동 견적서로 HQ랑 이야기해주세요~
- 80개 (더블룸 60 / 트윈룸 20) 
- 부가세 포함 132,000원

파트너스 하우스는 16일 부터 예약 가능하고
객실이 최대 9개인데..
VIP 룸은 더 필요하겠죠?

**Comment by soohyunpae** [comment]
넵 그럴게요. 감사합니다아~!

VIP는 키노트 3명 + 이사 현재까지 확인된 게 6명 + 라이언 하면 벌써 최소 10명이라 더 필요할 것 같긴 해요.

**Comment by soohyunpae** [comment]
@khseo 님, HQ에 공유할 호텔 정보 문서 따로 만들려다가 기존에 경희님이 정리해주신 문서에 시트 추가해서 공유하려고요. 그래서 제목 영어로 수정했는데 양해 부탁드려요^^;
https://docs.google.com/spreadsheets/d/1j4_B3NlArJ0MRp9lJ-D21jEsejqx-SDTEMeGJhTrjzc/edit

@nanshil 님 명동 앰베세더에서 최종 견적서 다시 오는대로 HQ에 보낼게요~

**Comment by khseo** [comment]
@soohyunpae 양해라뇨^ ^ㅎ
