### ISSUE TITLE
판촉물 위시 리스트 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#15]
- 보조밧데리 충전기 
  http://www.gmarket.co.kr/challenge/neo_affiliate/daum/daum_redirect.asp?target=http://www.gmarket.co.kr/challenge/neo_jaehu/jaehu_goods_gate.asp?goodscode=611106129&GoodsSale=Y&jaehuid=200002243&vkey=RLHIS0HZX24SKUXZ3933LKVUU4XMJ4 
- 바디슈트 / 아기 양말 
  https://www.facebook.com/photo.php?fbid=896616427065194&set=pcb.940368326006421&type=1&theater 
- 아티스트 콜라보 판촉물 
- 우산 
- 에코백 
- 성인 고급 양말 
- 집업 
- 대일밴드(?)

**Comment by nanshil** [comment]
이거 텀블벅 기념품으로도 고려해보는 거지요?
희정님이 여기 안계셔서 사무국게시판에도 공유할께요~

2015-06-02 14:02 GMT+09:00 jenniferkang notifications@github.com:

**Comment by jenniferkang** [comment]
아니 써밋용으로요~
텀블벅용으로 처음에 생각했는데..
생각해보니 5년동안 후원을 한 사람들하고도 또 겹치더라구요.

내일 네이버가면 여러가지 판촉물 많을꺼여요. 1층에 네이버 상품파는 샵이 있었던 것 같아요..
내일 함 둘러봅세요.

2015년 6월 2일 오후 5:20, nanshil notifications@github.com님이 작성:
