### ISSUE TITLE
로고 공모전 웹사이트 링크 추가하기

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/global-summit-#16]
https://summit.creativecommons.org/kr/
공모 요강 텍스트 및 참여하기 버튼 추가

@soohyunpae: https://summit.creativecommons.org
여기는 HQ 맷이 추가해야하겠죠?
- [x] 국문 원고 반영
- [x] 국문 세금 추가 원고 반영

영문 원고는 여기서 반영할 수 없습니다.
https://summit.creativecommons.org/
이 사이트는 HQ의 영역이라 matt이 추가해야 할 듯...

**Comment by soohyunpae** [comment]
네 지난 주에 맷한테 넣어달라고 말해두긴 했어요.
다 되시면 맷한테 직접 한번 전달해주세요. 저도 한번 더 말할게요~

**Comment by mozodev** [comment]
작업 확인용 URL (임시)
http://7143831f.ngrok.io/kr

![2015-06-09 11 08 25](https://cloud.githubusercontent.com/assets/1661950/8049270/ffbe7efe-0e97-11e5-8345-10f44acb66b6.png)

확인하시고 이상없으면 맷에게 PR 날리겠어요~
@creativecommonskorea/2015-summit

**Comment by nanshil** [comment]
- 보내주신 작업 확인용 임시 URL은 영문 페이지로 뜨는데.. 이게 맞나요?
- 첨부해주신 이미지로 확인하자면...
  상금 세금과 로고 다운로드 등 일부 텍스트 추가한 내용 제가 깃허브에 올려놓았어요! (
  https://github.com/creativecommonskorea/logo-summit/issues/14)
  이걸로 업데이트 해서 발행 부탁드릴께요~

2015-06-09 11:10 GMT+09:00 Yeongtaek Hong notifications@github.com:

**Comment by mozodev** [comment]
이게 실제 서비스되는 사이트 소스라 영문과 국문이 함께 있습니다.

http://7143831f.ngrok.io/kr

수정했는데 메일로 보셔서 그랬나보네요.. ㅎㅎ

2015년 6월 9일 오전 11:38, nanshil notifications@github.com님이 작성:

> - 보내주신 작업 확인용 임시 URL은 영문 페이지로 뜨는데.. 이게 맞나요?
> - 첨부해주신 이미지로 확인하자면...
>   상금 세금과 로고 다운로드 등 일부 텍스트 추가한 내용 제가 깃허브에 올려놓았어요! (
>   https://github.com/creativecommonskorea/logo-summit/issues/14)
>   이걸로 업데이트 해서 발행 부탁드릴께요~
> 
> 2015-06-09 11:10 GMT+09:00 Yeongtaek Hong notifications@github.com:
> 
> > 작업 확인용 URL (임시)
> > http://7143831f.ngrok.io
> > 
> > [image: 2015-06-09 11 08 25]
> > <
> > https://cloud.githubusercontent.com/assets/1661950/8049270/ffbe7efe-0e97-11e5-8345-10f44acb66b6.png>
> > 
> > 확인하시고 이상없으면 맷에게 PR 날리겠어요~
> > @creativecommonskorea/2015-summit
> > https://github.com/orgs/creativecommonskorea/teams/2015-summit
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/creativecommonskorea/global-summit-/issues/16#issuecomment-110198447>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommonskorea/global-summit-/issues/16#issuecomment-110201312
> .

## 

[image: cckorea_logo.png]
- 홍영택 \* Yeongtaek, Hong
  
  _CCKOREA_ | _Codenamu_

_Tel_ 070-7618-0321  _Mobile_ +82 (0)10-9283-9754

_Address *_서울특별시 마포구 와우산로19길 21 (서교동) 5층*

_Sites  CCKOREA_ (cckorea.org) _공유허브 *(_sharehub.kr http://sharehub.kr/*)
-    코드나무 _(_codenamu.org http://codenamu.org/_)  *Code for Seoul (_
  codeforseoul.org)

**Comment by soohyunpae** [comment]
공모하기 페이지에서 위에 cc global summit 에서 g만 소문자네요~

그리고 english 클릭하면 cc사이트로 연결되는 건 임시인거죠?

**Comment by mozodev** [comment]
@soohyunpae 
1. 공모하기 페이지는 
   http://logo.cckorea.org/ko
   여기 말씀하시는거죠?
   global => Global 수정했습니다.
2. english 링크
   http://7143831f.ngrok.io/kr/ 
   이 웹사이트에 우측 상단에 있는 English 링크라면 
   http://summit.creativecommons.org/ 로 연결되는게 맞는건데요...
   지금 여기는 서밋 웹사이트니까 서밋 영문 사이트로 가는 링크...
   제가 잘못 이해했나요?

**Comment by soohyunpae** [comment]
1. 아 네, 근데 영문 페이지는 아직 g가 소문자네요~ 이것도 부탁드려요.
2. 엇 지금은 맞네요~ 이상하게 아까 클릭했을 땐 서밋 영문 사이트가 아니라 cc 홈페이지로 연결되더라구요. 네 이건 문제 없네요! :)

**Comment by mozodev** [comment]
1. 아 작업은 하고 서버에 반영을 안했네요... 적용했습니다.
   ~~

**Comment by soohyunpae** [comment]
앗 그리고 죄송하지만 하나 더요~
영문 페이지에는 공모전 결과 발표일이 빠졌네요~
아래처럼 Results: July 22, 2015 한 줄 추가 부탁드려요!

Selection: Entries will be judged jointly by the public and the CC Selection Committee
1st Round: Public voting (July 1 - July 8)
2nd Round: CC Selection Committee voting (July 9 - July 16)
Results: July 22, 2015

이 문서에 빨간색으로 표시되어 있어요.
https://docs.google.com/document/d/1L1uW30olOTa6MCZTdZcHya9DDuivuyfueOAgSJ4CGQ8/edit

**Comment by mozodev** [comment]
근데 자꾸 서밋 페이지에 로고 웹사이트 이슈를 적어주셔서 왔다갔다 하네요...ㅎㅎㅎ

@soohyunpae 
어쨌든 본문에도 적어놨는데.. https://summit.creativecommons.org/ 여기는 matt이 쓴 코드로 우리가 제작한 /kr 페이지와는 디자인도 완전히 달라서 제가 원고를 추가할 수가 없습니다. 더 혼란스러워질거 같아요...

@nanshil
여기서는 국문 화면만 봐주시면 됩니다. 국문 세금 관련 추가된 원고까지 반영 완료!
http://7143831f.ngrok.io/kr/

**Comment by soohyunpae** [comment]
아이고 제가 그랬군요...죄송해요~ㅎ
네 위에 추가해달라고 부탁드린 건 summit.creativecommons.org 가 아니고 logo.cckorea.org의 영문 페이지 텍스트에 추가해달라고 부탁드린 거에요~

https://docs.google.com/presentation/d/1nPlWd_wpettVAlSVyelC--d9kaky3d4aQsQctQ-b2cg/edit#slide=id.g9fa8454d9_0_123
위의 문서를 보시라고 했어야 했는데 제가 모바일로 보면서 빨리 피드백 드리려고 하다보니 헷갈리게 피드백을 드렸네요.
위 문서에 빨간색으로 표시한 것처럼 넣어주시면 될 것 같아요!

**Comment by mozodev** [comment]
@soohyunpae 
국문 원고에는 최종 발표일 뿐만 아니라 세금 관련 원고도 들어갔는데 지금 원고에는 그런 내용이 없는데요... 없이 그냥 최종 결과 발표일만 추가하면 될까요?

추가한 국문 원고는 아래와 같습니다.

```
   수상 특전    : 
상금 500달러 (상금 수령과 관련하여 세금 등이 발생할 수 있음. 관련 안내는 수상자에게 직접 연락 예정)
Summit 현장에서 수상자 및 수상 작품 소개 
   참가 가이드 :  
Creative Commons 를 상징하는 시각적 아이덴티티로서 CC 로고는 최근 MOMA 전시와 Noun Project 의 프로젝트를 통해서도 세계의 인정을 받았습니다. 이제 이러한 CC의 아이덴티티에 여러분의 창의력과 재능을 입혀 2015년 CC Global Summit을 나타내는 로고를 만들어 주세요. 
당선 로고는 온라인과 오프라인 프로그램, 관련 상품의 디자인에 사용됩니다
로고 다운로드: https://creativecommons.org/about/downloads 
```

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 
맷에게 코드 보냈습니다~

Added details and link to logo competition website.
https://github.com/creativecommons/global-summit-/pull/28
