### ISSUE TITLE
웹사이트 관리 이슈

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#18]
로고공모전 이슈에서 따로 빼서 이슈 만들었습니다.
HQ와 논의할 내용 정리해보아요.

다음주 수요일 오전에 HQ써밋팀 회의에서 웹사이트 관리에 대한 명확한 가이드라인/권한 관련 이슈 정리해서 제기하는 게 좋을 것 같아요. (그 전에 문서로 먼저 공유하려고 해요.)
- 현재 상황
  국문 사이트 관리 권한 영택님에게 달라고 Matt에게 요청한 상태
- 앞으로 온라인에 업데이트 되어야할 내용 
  (아래 영택님 올려주신 것 일단 긁어왔어요.)
1. 행사 사전 홍보
   세션, 연사 정보 업데이트
   참가자, 연사 등록 관리
   세션 프로그램 제안받아서 확정되면 정보를 업데이트해서 본격적으로 서밋 홍보를 해야하는데 현재 랜딩 페이지로 계속 갈건지... 아마도 새로운 디자인으로 구축하는게 맞겠죠.. 이건 어느정도 세션이 결정되면 음 근데 2번이 결정되면 바로 구축을 해야겠네요..
2. 행사 진행 이후 커뮤니케이션
   그리고 예전에 현숙님이 컨퍼런스용 사이트 예를 몇 개 드시면서 이런거 사용해보면 좋겠다고 하셨는데... 예를 들면 실제 행사가 시작되서 세션 진행하면서 즉시 질문이나 의견을 댓글로 달고 세션 평가도 하고 뭐 그런...
   어쨌든 이건 HQ하고 합의가 된건지 의사결정이 필요한 문제일 것 같고요...

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 

저도 계속 생각을 해봤는데 제 의견은 
웹사이트는 HQ, 씨씨코리아 완전히 분리해서 가는게 맞는 것 같습니다. 

도메인도 
summit.creativecommons.org
summit2015.cckorea.org
이렇게 완전히 분리해서 행사 지원 신청, 결제, 프로그램 정보 공유, 수정 등이 원할할 거 같습니다.

지원 신청, 결제만 따로 페이지를 만든다고 해도 하나의 시스템(HQ가 됐든 우리가 됐든)으로 통합하는게 만만치 않습니다. 얻을려고 하는거에 비해 들여야하는 공이 너무 많습니다. 
그냥 개념적으로 생각해봐도 서로 완전히 다른 걸 억지로 통합하려는 거 같기도 하고요..

제 생각에는 서밋 홈페이지를 국영문 하나의 도메인으로 통합하려고 하는 목적이....
세션에 참가하는 사람들 전체 목록을 보여주자는 거 같은데 그걸 제외하고는 어떤 이득이 있는지 알 수 없습니다.
있으면 좋긴 하지만 그게 그렇게 중요한 일인지 잘 모르겠습니다. 
억지로 하자면 api endpoint 만들어서 세션 참가자 데이터를 주고 받고 할 수는 있습니다만 맷과 제가 동시에 번거롭겠죠. 행사 신청 받는 기간 동안 실시간으로 변할테니까요..
제 생각에는 맷은 동의하지 않을 거 같습니다.

우선 분리냐 통합이냐 이걸 우선 결정해야할 문제로 제안합니다.
그리고 제 의견은 분리입니다.

**Comment by jenniferkang** [comment]
@soohyunpae  
써밋 홈페이지 디자인은 슬로워크에서 맡을 예정입니다. 
내일 2시에 써밋 웹사이트 개발 때문에 김범준님이랑 미팅을 하기로 했어요. 
사이트 구축은 @khseo 님께서 맡기로 했어요. 제가 물론 서포트할껍니다.

**Comment by soohyunpae** [comment]
넵~! 그럼 내일 2시 미팅 전후에 HQ에 제안할 웹사이트 관리 관련 내용도 정리해보면 좋겠네요.
