### ISSUE TITLE
HQ Program Committee 

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#19]
영문 사이트에 Call for Participation and Proposals가 오픈했는데요.
Program Committee에서 들어온 세션 제안서를 검토하고 의견을 나눈 후 최종 프로그램을 확정합니다.
HQ 스탭 몇 명, 저, affiliate 대표 지역별로 고르게 몇 명, CC아르헨티나, OKF 등 관련 커뮤니티 대표 한 두 명 이렇게 구성되어 있구요, 한국 대표로 저희 발룬티어 한 명을 추가하기로 얘기해서 공지를 얼마전에 올렸었는데, 오주영님이 흔쾌히 수락해주셨습니다~짝짝짝

프로그램 관련 내용(특히 HQ 쪽 관련 내용)은 저희팀 전체에 공유가 어려우니 여기에 제가 수시로 정리해서 올릴게요.

**Comment by jenniferkang** [comment]
오예~~ 오주영님을 깃허브로 초대부터 해야겠어요.
오주영님이 참여하게 되었다고 페북 댓글로 알려주세요.

주영님이 어쩌면~ 보행기 들고 울 사무실에 올지도 몰겠어요.
유모차에 서연이랑 주오랑 둘이 번걸아가면서? ^^
사실 그래도 되는데 머리 아플때에 돌아가면서 애 봐도 되고.

2015년 6월 19일 오전 10:18, Soohyun Pae notifications@github.com님이 작성:

> 영문 사이트에 Call for Participation and Proposals가 오픈했는데요.
> Program Committee에서 들어온 세션 제안서를 검토하고 의견을 나눈 후 최종 프로그램을 확정합니다.
> HQ 스탭 몇 명, 저, affiliate 대표 지역별로 고르게 몇 명, CC아르헨티나, OKF 등 관련 커뮤니티 대표 한 두 명
> 이렇게 구성되어 있구요, 한국 대표로 저희 발룬티어 한 명을 추가하기로 얘기해서 공지를 얼마전에 올렸었는데, 오주영님이 흔쾌히
> 수락해주셨습니다~짝짝짝
> 
> 프로그램 관련 내용(특히 HQ 쪽 관련 내용)은 저희팀 전체에 공유가 어려우니 여기에 제가 수시로 정리해서 올릴게요.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommonskorea/global-summit-/issues/19.

## 

_강현숙  *Jennifer Kang_[image: cckorea_logo3.png]*

 CCKOREA | 사무국장

 _Twitter @hskang      Tel_ 070-7618-0321

 hskang211@gmail.com

_Address *_마포구 서교동 363-20 5층 \* (오시는길
http://map.naver.com/?dlevel=12&pinType=site&pinId=12231010&x=126.9218731&y=37.5511880&enc=b64
)

_Sites  CCKOREA_ (cc http://cckorea.org/korea.org http://cckorea.org/)*
공유허브 _(_sharehub.kr http://sharehub.kr/_)  *코드나무 *(_codenamu.org
http://codenamu.org/*)

**Comment by soohyunpae** [comment]
넵ㅎ
CC어린이집 오픈하나요~:)
