### ISSUE TITLE
글로벌 서밋 이슈 관리

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/global-summit-#2]
@creativecommonskorea/bureau 
HQ처럼 우리도 여기서 편하게 우리말로 논의하면 좋을 것 같아요

**참고**
이 게시판 문법은 마크다운이라고 하는 형식인데요
지원하는 형식 규칙은 [Markdown supported](https://guides.github.com/features/mastering-markdown/) 여기를 참고하시면 됩니다.

HQ 레포지토리 이슈로 링크도 걸 수 있어요.
참조 링크 형식

```
단체/레포명#{이슈 숫자 아이디} 
creativecommons/global-summit-#{이슈 숫자 아이디}
```

**Comment by soohyunpae** [comment]
@mozodev 제가 이슈를 몇개 작성했는데요, assignee이나 milestone 지정은 안되더라구요. collaborator여서 그럴까요?

**Comment by soohyunpae** [comment]
좀 찾아보니까 fork 된 repository의 경우 commit 한 게 내 repository에 안뜬다는 설명이 있는데...그거랑 관련이 있을까요?
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by soohyunpae** [comment]
@mozodev 님~ 여기서 이슈 assign이나 milestone 설정은 안되나요?

**Comment by mozodev** [comment]
되는거 같은데요 모바일 화면에는 ui가 없네요. 맨 밑으로 가면 desktop version 링크 클릭하면 나와요.

**Comment by soohyunpae** [comment]
흠 제가 노트북으로 하고 있거든요...내일 사무실 계시면 가서 보여드리고 좀 여쭤볼게요~!

**Comment by mozodev** [comment]
@soohyunpae 이슈 할당이나 마일스톤은 확인해보니 팀 권한을 덜드려서 그런 거였어요.. 이제 될 거에요.. 늦게 봐서 죄송~ ㅎㅎ
