### ISSUE TITLE
키노트,강연자 섭외 목록 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#22]
TJ Bliss — 확정
휴렛 재단 교육 프로그램 담당
Program Officer, Education Program, Hewlett Foundation
전 미국 아이다호 주 교육청 평가책임국장
전 국제 초중등 이러닝 협회(iNACOL)  OER 정책 연구원
http://www.hewlett.org/about-us/staff/tj-bliss

Fred Von Lohmann
https://en.wikipedia.org/wiki/Fred_von_Lohmann
현 Google 저작권 담당 수석 변호사
전 전자프론티어재단(Electronic Frontier Foundation) 지재권 전문 수석 변호사
전 버클리 법과기술센터 방문학자
캘리포니아 올해의 변호인상 등 수상
The American Lawyer와 Billboard 잡지에서 ‘2010년 지식재산권 분야의 가장 영향력 있는 25인’에 선정
스탠포드 로스쿨 법무박사

Parker Emmott
현 Flickr 제품 관리 이사? Director of Product Management at Flickr
노스웨스턴대  경영학 석사
IDEO 비즈니스 디자인 대회 우승

Lila Tretikov
현 위키미디어 재단 사무총장 Executive Director, Wikimedia Foundation
https://www.linkedin.com/in/lilatretikov
https://wikimediafoundation.org/wiki/User:LilaTretikov_(WMF)

Damon Sicore
현 위키미디어 재단 엔지니어링 담당 이사
Wikimedia Foundation Vice President of Engineering
전 모질라 Vice President of Engineering
전 Edmondo Vice President of Engineering
https://blog.wikimedia.org/2014/09/29/damon-sicore-joins-wmf-as-vice-president-of-engineering/

Andrew Stott (참고로..지난번에 말씀하셨던 영국 data.gov.uk 만든 사람이요.)
http://live.worldbank.org/experts/andrew-stott
UK Transparency Board Member and World Bank Consultant

**Comment by jenniferkang** [comment]
@soohyunpae 오픈디자인에 있는 사람들 초대하는 것도 좋을 것 같은데.  
어떠심요?

**Comment by soohyunpae** [comment]
현재까지 참석 확정 이사 명단입니다.
Jay Yoon (obvious, I know but still counts!)
Eric Saltzman
Laurie Racine
Molly Van Houweling
Paul Brest
Paul Keller
Renata Avila

불참
Larry Lessig, Tom Rubin, Hal Abelson

**Comment by soohyunpae** [comment]
@jenniferkang HQ에 오픈디자인 관련 섭외 제안했고요, 오픈디자인나우 책에도 나온 Shapeways.com 팀 컨택 중이에요. 좀더 업데이트 되는대로 공유할게요.

**Comment by jenniferkang** [comment]
@soohyunpae  손님. 요차이 벤클러 교수 섭외시에 우리쪽에서 공식 행사외에 방통위원장 미팅이나 이런거 있는거 메일 공유하기로 했었지요? 
겸사 다른건데. 우리 어워드 의견도 공유하면 어떨까요?

**Comment by soohyunpae** [comment]
@jenniferkang 손님에서 한참 생각했어요 ㅋㅋㅋㅋ 뭘까...왜일까....

네 그 내용 공유했어요~ 벤클러한테 부탁하고 싶은 주제 있으면 그것도 생각해보고 주겠다고 했었어요.
생각해보고 며칠 내로 한번 공유하면 좋을 것 같아요.

어워드 의견 오늘 얘기할게요~

**Comment by jenniferkang** [comment]
전 진짜 왜그러는걸까요.. 미쳤나봐요... ㅋㅋ
