### ISSUE TITLE
로고 공모전 일정 변경건 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#27]
로고 공모전 마감이 내일이네요. 

@mozodev 영택님 : 개발 일정 검토해 주세요. 
@soohyunpae 배수현님 : 일정 변경하는거 HQ랑 논의하시고요. 2차 심사 - 심사 위원 구성도 부탁드립니다. 

현재)  
접수 기간 2015. 6. 8 ~ 2015. 6. 30 (UTC)
심사 방법
1차 온라인 투표: 7.1 ~ 7.8
2차 심사위원 평가: 7.9 ~ 7.16
수상작 발표: 2015. 7. 22(수) 

수정안) 
1. 6. 8 ~ 2015. 7. 7 (UTC)
   심사 방법
   1차 온라인 투표: 7.8 ~ 7.15
   2차 심사위원 평가: 7.16 ~ 7.21
   수상작 발표: 2015. 7. 23(목)

**Comment by soohyunpae** [comment]
심사방법을 구체적으로 정해서 제시하는 것이 좋을 것 같아요.

1차 온라인 투표로 5개? 3개 정도 1차로 뽑고 
2차는 HQ 써밋위원회 + CC 프로그램 위원회 (HQ 몇 + 한국 한명 + affiliate 지역별 대표 몇 + CC 아르헨티나 + 기타 한두명)에서 심사 및 투표로 최종 결정하는 것이 어떨까요?

@jenniferkang @nanshil 의견 부탁드려요~

**Comment by soohyunpae** [comment]
일단 일정이 급하니까 이 안으로 메일은 보냈습니다. 
심사 관련해서 다른 아이디어 있으면 추가로 주고 받으면 될 것 같아요.

**Comment by soohyunpae** [comment]
HQ에서 별다른 이의는 없습니다.
@mozodev 이미 7월 1일이라 빨리 수정 반영하고 affiliate 들한테랑 sns로 공지해야할 것 같아요~ 부탁드려요!

**Comment by mozodev** [comment]
@soohyunpae ㅇㅇ starting working on it!

**Comment by mozodev** [comment]
@soohyunpae 연장 공지 메시지를 간단히라도 적어주는게 좋을 것 같은데요 갑자기 띡 아무 변화도 없이 숫자만 바꾸면 글씨도 작고 잘 모를 것 같아서요.. 이미 등록한 사람들한테는 메일이라도 보내줘야할까요?

대략 이런 식으로 보이게 될 겁니다..
![2015-07-01 9 44 42](https://cloud.githubusercontent.com/assets/1661950/8445280/d7341706-1fd5-11e5-939c-1c9271abe91f.png)

제안)
공모를 1주일간 연장합니다. 아래 일정을 참고해주세요.

**Comment by soohyunpae** [comment]
스크린샷이 다른건가봐요~ 안보여요 ㅎ 
네 제안해주신 텍스트는 빨간색이라든가 잘 보이는 색으로 표시해주시면 좋을 것 같아요!
일단 국영문 페이지 모두 일정부터 바꿔주시면 좋을 것 같아요~ 미국사람들 퇴근하기 전에 빨리 알려주려구요~

영문 추가 수정 텍스트는 제가 지금 작성해볼게요.
써밋 뉴스레터 가입한 사람들한테도 공지 메일 한번 보내주면 좋을 것 같아요.

**Comment by soohyunpae** [comment]
영문 페이지 공지글 상단에도 아래 텍스트 하나 추가해 주세요~!

Update: We're now pleased to announce that the deadline for the Logo Design Competition has been extended to July 7! Please check the updated schedule below.

**Comment by soohyunpae** [comment]
@mozodev 님 업데이트 적용되시면 바로 알려주세요~ HQ에 알려서 sns랑 메일링리스트에도 뿌리려구요!

**Comment by mozodev** [comment]
https://logo.cckorea.org/ko
https://logo.cckorea.org/en
done!

**Comment by soohyunpae** [comment]
유후!

**Comment by mozodev** [comment]
@soohyunpae https://github.com/creativecommons/global-summit-/pull/36 서밋 웹사이트에 공모전 일정 수정 관련한 코드 맷 한테 보냈습니다~  https://summit.creativecommons.org/kr/
