### ISSUE TITLE
HQ 깃헙 팀 꼬인 듯...

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/global-summit-#3]
깃헙에서 레포지토리 관리는 
org 단체 밑에 team 팀을 만들고 그 팀을 레포지토리에 지정해줍니다.
팀이 중요한 건 코드를 쓰고 지울 수 있는 권한과 레포지토리 생성 및 삭제 등 관리 권한을 줄 수 있어서 그런겁니다.

깃헙 단체 관리자 입장에서는 사실 팀과 권한이 민감하고 중요한 문제입니다.
믿을 수 있는 사용자라도 보안 관리 개념이 없는 사용자에게 관리 권한을 주면 해당 깃헙 계정이 해킹당할 경우 모든 레포지토리를 지울 수도 있거든요.. 그래서 관리 권한이 있는 계정은 two factor 인증같은 걸로 계정을 좀 더 보호해야 하죠..

어쨌든... 
지금 creativecommons/global-summit 이 레포지토리에 @soohyunpae 님이 아마도 서밋 팀으로 되어 있을거 같은데 그 팀 안에 있는 사람들만 참조할 수 있는거죠. 사실 이슈는 열려있어서 특별한 권한이 없어도 쓸 수 있어요.
이게 팀들이 다 비공개로 되어 있어서 자신이 속한 팀만 볼 수 있습니다. 아까 말씀드렸듯이 팀별로 권한이 있는 레포지토리가 각각 다르거든요...

| username | team | repository |
| --- | --- | --- |
| @mozodev | community | [creativecommons/flaming-octo-robot](https://github.com/creativecommons/flaming-octo-robot) |
| @nanshil | affliates | [creativecommons/stateofthe](https://github.com/creativecommons/stateofthe) |

저와 난실님은 각각 팀, 레포지토리가 저런 상태입니다. ㅋㅋㅋㅋ

**Comment by mozodev** [comment]
이걸 어떻게 정리해서 matt 한테 이야기할지 고민 중입니다. ㅎㅎ

**Comment by soohyunpae** [comment]
아아 그렇군요~

그런데 그럼에도 불구하고 원래 저희 사람들을 global-summit 레파지토리 팀에 추가한다고 했었거든요. 프로젝트 관리 목적으로 만든 팀이라 우리 쪽 담당자한테 이슈 할당하려고 했던거라서요. 그런데 굳이 팀안에 안들어가도 레파지토리에서 이슈 작성까지는 가능하다는 말씀이시죠? 영택님도 굳이 들어가야할 필요는 없으신거구요?

그러면 제가 난실님과 현숙님께 최종 확인해보고 추가가 필요할거 같으면 matt 한테 다시 얘기할게요.
감사합니다^^

**Comment by mozodev** [comment]
맷이 저를 난실님과 같은 팀에 넣었네요 creativecommons/affliates 저에게 수정 작업을 할당해서 마무리했어요.
그리고 affliates 팀을 서밋 저장소에 할당했어요. 이제 그 서밋 이슈에서 난실님과 제 아이디도 참조할 수 있어요. 
현숙님은 다른 팀에 계신가? 어쨌든 이 이슈도 닫습니다~
