### ISSUE TITLE
로고공모전 마무리

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#30]
먼저 현 상황 업데이트해드립니다.
로고 공모전 2차 심사가 오늘 오후까지 완료될 예정이에요. 아직 미주 지역은 수요일 시간이 좀더 남아서 그때까진 기다려야할 것 같아요. 
22명 중 현재 16명 투표한 상태이고, 슬로워크 추천 로고가 유력해 보여요.

이후 절차
- 오늘(목) 오후 심사 완료 후 결과 공유 (우리+심사팀+HQ)
- HQ에 당선작 공지, 상금 등과 관련한 다음 절차 확인
- HQ에 로고 정책 및 수정 관련 가이드라인 요청
- 수정 관련 가이드라인 슬로워크에 전달
- 당선자 개별 연락+수정 필요 사항 전달
- 웹사이트에 결과 발표 (영문, 국문 동시) - 미국 시간에 맞추려면 늦으면 토요일 저녁까지. --> 우리 텍스트 미리 준비해놓고 토요일에 맞춰서 업데이트 가능할까요? 시차를 고려하면 영문에 내일 업데이트는 무리일 것 같아서요.
- 슬로워크 로고 수정
- 최종 로고 시안 확인 및 확정
- 상금 전달 (HQ 일)

보시고 일정 관련 문제나 빠진 부분 있으면 피드백 주세요~
@nanshil @mozodev @jenniferkang @khseo

**Comment by soohyunpae** [comment]
HQ에서 온 피드백입니다.
기본적으론 로고 공모전의 취지상 가능하면 변경은 최소한으로 해야한다는 입장이구요.
아래 네가지를 당선자에게 수정 요청하자고 합니다.
- Korea 철자 수정 
- 날짜 사이 - 간격 조정
- 오른쪽 상단 트레이드마크(r) 표시 삭제
- revert to our font for the double-c and circle --> cc 마크의 선을 원래 모양대로 굵게 하자는데, 이것도 이견은 있어요. 이건 우리가 원하는 방향으로 의견 주면 될 것 같아요. 

제 기억에 저희는 슬로워크가 로고 색상 등을 바꾸고 싶어했던 걸로 알고 있는데, 맞는지요? 그것에 대해선 좀 반대가 있을 수도 있을 것 같아요. 일단 저희 디자이너가 디자인 관점에서 추가 수정 의견 있을 수도 있다고 얘기는 했어요.

상금 관련 동의서 등 법률 문서는 준비되었어요. 위의 수정 사항 정리되는대로 당선자에게 연락하면 될 것 같아요.

**Comment by soohyunpae** [comment]
참고로 동의서 양식입니다~ 
주된 내용은 저작권, 상표권등 일체의 권리 양도한다는 내용, 500달러 주고 받는다는 내용, 미국법에 따른다는 내용입니다.
https://docs.google.com/a/creativecommons.org/document/d/1FVNm9-r-XjR5zqTpOz3XOQl-EcZsEkZqXPZ85sY4f7o/edit?usp=sharing

**Comment by mozodev** [comment]
웹사이트는 아래 내용으로 원고 교체 작업 진행합니다!

최종 당선안
https://logo.cckorea.org/ko/node/83

**Comment by soohyunpae** [comment]
@mozodev 네~ 그전에 제가 먼저 당선자에게 연락해서 동의서 보내고 디자인 변경사항 곧 전달하겠다고 할게요. 답변 오는대로 알려드릴게요!

**Comment by soohyunpae** [comment]
@mozodev 영택님 당선자 연락처 정보 부탁드려요!

**Comment by mozodev** [comment]
@soohyunpae 이 저장소는 공개되어 있어서 메일로 드릴께요~

**Comment by mozodev** [comment]
서밋 홈페이지 수정한 코드 보냈습니다. 
https://github.com/creativecommons/global-summit-/pull/48
