### ISSUE TITLE
강연자 - 도희성 대표 소개글 수정 요청 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#33]
@mozodev 님
강연자 - 도희성 대표 소개글 수정 부탁합니다. 

원트리뮤직은 '라임덕비즈'라는 시스템을 통해 저작권료를 낮추도록 하여 저렴한 가격으로 매장에 음원을 제공하고 있다.

-) 

CCL음원을 활용한  매장음악서비스를 하는 원트리뮤직의  대표이다. 
커피빈, 테크노마트 등이 주요 고객사이며  뿐만 아니라 조PD의 새음반의 음원을 매장음악 서비스를 통해서 홍보하는 등 다양한 시도들을 하고 있다. 

너무 길면 아래  내용으로 해 주세요. 

CCL음원을 활용한  매장음악서비스를 하는 원트리뮤직의 대표로  커피빈, 테크노마트 등이 주요 고객사이다.

**Comment by mozodev** [comment]
https://summit.cckorea.org/speakers.html
