### ISSUE TITLE
연사 정보 수정 - Paul Stacey 

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#34]
@mozodev님 이것도 부탁드려요~!

Paul Stacey
CC 글로벌 러닝(learning) 대표
캐나다 브리티시컬럼럼비아주를 중심으로 OER 활동을 하며 정부 및 연구기관들에게 CCL을 전파하는 데 큰 역할을 하고 있다.

Paul Stacey
CC 글로벌 오픈 비즈니스 이니셔티브 담당
CC 글로벌의 오픈 비즈니스 이니셔티브를 이끌며 CCL 콘텐츠 등 공유저작물을 이용한 오픈 비즈니스 모델을 발굴하고 그 잠재력을 알리는 일에 집중하고 있다.

**Comment by mozodev** [comment]
https://summit.cckorea.org/speakers.html
