### ISSUE TITLE
저작위 -) 한국저작권위원회 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#37]
@mozodev 16일에 저작위 창조자원화 포럼으로 되어 있는데요. 
한국저작권위원회로 해 주세요. 변경 부탁합니다. 

다른 곳에서는 그렇게 되어 있는 곳 없겠죠?

**Comment by mozodev** [comment]
https://summit.cckorea.org/programs.html?day=1016
