### ISSUE TITLE
국문 랜딩 페이지용 배너 제작 및 cckorea.org 반영

### ISSUE THREAD

**Issue by mozodev** [creativecommonskorea/global-summit-#4]
658x270

![logo](http://summit.cckorea.org/img/header-title.png)
+
![text](http://summit.cckorea.org/img/mailing-heading.png)

공유와 개방의 가치를 믿고,
긍정적인 변화를 만들어내는 사람들의 즐거운 축제가
10월, 서울에서 열립니다.

**Comment by mozodev** [comment]
![2015-cc-gs-banner](https://cloud.githubusercontent.com/assets/1661950/7408435/a6271ee6-ef57-11e4-8f28-76e7cb726acc.jpg)

**Comment by mozodev** [comment]
http://cckorea.org/xe/
일단 도메인은 영문 사이트로 연결 이후에 맷이 배포해주면 링크 수정하겠습니다.

**Comment by nanshil** [comment]
영택님~ 죄송한데.. 우측 텍스트 폰트 크기 조금만 줄여주시면 안될까요? 텍스트가 너무 커보여서요;;;

2015년 4월 30일 목요일, Yeongtaek Hongnotifications@github.com님이 작성한 메시지:

**Comment by jenniferkang** [comment]
아직 수정안하셨다면. [바로가기] 버튼은 삭제해 주세요.  없어도 될 것 같아요. 
디자이너 홍영택님. ^^ 부탁합니다.

**Comment by mozodev** [comment]
![2015-cc-gs-banner-v2](https://cloud.githubusercontent.com/assets/1661950/7412815/4ba3e434-ef81-11e4-940f-7d9fa4c1db66.jpg) ㅎ

**Comment by nanshil** [comment]
좋아요! :)

**Comment by mozodev** [comment]
:+1:
