### ISSUE TITLE
발표 순서 변경 / 제목 변경

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/global-summit-#40]
트랙2: 오픈 비즈니스
오픈 비즈니스의 성공 전략_Paul Stacey_CC 글로벌 러닝(Global Learning) 대표
Photo Commons_Andy Yang_500px CEO
공개된 CCL 음원의 비즈니스 모델_도희성_원트리즈뮤직대표

트랙 4. DIY
오픈소스 인공위성 프로젝트 송호준_미디어 아티스트
프로그래밍의 첫걸음 엔트리  김지현_엔트릭교육연구소 대표
3D 프린터 기술의 진화 Michael Weinberg_Shapeways 법률고문

@mozodev 님 변경 부탁드리고요.
송호준 작가는 제목 수정도 해 주세요

우리 순서 바뀐거여요. 영문 사이트에서도 변경을 해야하거든요. @soohyunpae 님 영문사이트 변경할 수 있는 권한 가지고 계세요?  
그리고 지금 세션 좀 바뀌고 이런것들 정리해서 영택님에게 알려주세요.

**Comment by soohyunpae** [comment]
넵~ 변경하고 다른 것 영택님께 전달해드릴게요

On Thursday, October 1, 2015, jenniferkang notifications@github.com wrote:

> 트랙2: 오픈 비즈니스
> 오픈 비즈니스의 성공 전략
> 
> _Paul Stacey_CC 글로벌 러닝(Global Learning) 대표 Photo Commons_Andy Yang_500px
> CEO 공개된 CCL 음원의 비즈니스 모델_도희성_원트리즈뮤직대표
> 
> 트랙 4. DIY
> 오픈소스 인공위성 프로젝트 송호준
> _미디어 아티스트 프로그래밍의 첫걸음 엔트리 김지현_엔트릭교육연구소 대표
> 3D 프린터 기술의 진화 Michael Weinberg_Shapeways 법률고문
> 
> @mozodev https://github.com/mozodev 님 변경 부탁드리고요.
> 송호준 작가는 제목 수정도 해 주세요
> 
> 우리 순서 바뀐거여요. 영문 사이트에서도 변경을 해야하거든요. @soohyunpae
> https://github.com/soohyunpae 님 영문사이트 변경할 수 있는 권한 가지고 계세요?
> 
> 그리고 지금 세션 좀 바뀌고 이런것들 정리해서 영택님에게 알려주세요.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommonskorea/global-summit-/issues/40.

## 

Sent from Gmail Mobile
