### ISSUE TITLE
16일 프로그램 수정

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#41]
16일 
영택님 16일 프로그램 수정 부탁드려요~
https://docs.google.com/spreadsheets/d/1G7sM9TPhSj936R68g3vU95kXOwYCxfjtHFhDcqdp6mw/edit#gid=1022636677
아래 리스트 보시고 이 문서에 업데이트 된 것으로 수정해주시면 됩니다! :)

중앙박물관 
- 공유도시 (소강당) -> 대강당
- 오픈글램 (대강당) -> 소강당
- 소강당에 공정이용 삽입
- 15:30 오픈데이터 --> OER
- 14:00 세미나룸 세션 제목: 저작권 개선 --> 저작권 개혁

한글박물관 
- 강의실 2 디지털 기술과 공유 <- 삭제
- 15:30 한글박물관 강의실 2 - 오픈 데이터로 변경
- 15:30 강의실 1 세션 제목: 저작권 개선 --> 저작권 개혁

**Comment by mozodev** [comment]
15일 변경분까지 적용했습니다.
