### ISSUE TITLE
로고 공모 페이지 관련 

### ISSUE THREAD

**Issue by nanshil** [creativecommonskorea/global-summit-#6]
로고 공모 관련하여 상의합니다.
그동안 논의했던 대로 아래 2가지 방법이 가능합니다.
- 1안:  참가자들이 직접 자기 작품을 올리고(플리커 연동) -> 1차 공개 투표, -> 2차 CCKOREA 내부 심사 -> 3차 HQ /  Affiliate 심사 
- 2안: 이메일 접수 -> 1차 CCKOREA 내부 심사 -> 2차 Q /  Affiliate 심사 -> 3차 공개 투표 
- 일정 관련 
  1안으로 할 경우, 개발 일정이 다소 소요되어서
  지금 목표는 5월 27일 ~ 6월 30일까지 모집 기간으로 하는 것으로 계획하고 있어요! 
- 논의 사항 
  1안으로 할 경우, 도메인을 저희가 마음대로 설정해도 되는지 (지금도 Matt이 발행을 안해주는데;;;) 이슈가 있네요~ 
  더불어 1안으로 할 경우 사이트는 영문으로 하고, 한글 설명은 저희 게이트웨이 페이지에서 해주면 되겠죠? (국문 사이트까지 만들 필요는 없겠죠?) 

의견 부탁드려요~ @soohyunpae @jenniferkang

**Comment by soohyunpae** [comment]
- 저는 단순하게 생각할 때는 더 공개되는 방식인 1안이 좋은 것 같아요. 그런데 디자인/개발 리소스를 고려해야하니...
  HQ에 두가지 안을 제시하고 디자인이 HQ 인력으로 가능한지, 도메인은 우리 마음대로 설정해도 될지 미리 한번 확인해보는 것도 좋을 것 같아요. 답변에 따라 우리가 둘중에 결정할테니 피드백 달라고 얘기하고요.
- 심사 과정 관련 의견입니다. 퍼블릭 -> CCKOREA -> HQ/Affiliates 보다 퍼블릭 -> Affiliates -> HQ/CCKOREA 로 하는 건 어떠세요?

**Comment by jenniferkang** [comment]
저도 1안이 좋고요.
다만 1안의 2차투표를 CCKOREA + CC HQ + CC Aff 모두 다같이 하는걸로 해요

2015년 5월 12일 오전 11:54, Soohyun Pae notifications@github.com님이 작성:

**Comment by nanshil** [comment]
로고 공모 페이지 기획서입니다.
- 투표는 1차 온라인, 2차 심사위원 투표로 명기했습니다.
- 영택님! 기본 메뉴는 정리했는데 혹시 추가해야할 페이지나 텍스트 있으면 알려주세요~ @mozodev 
- 션님! 번역 부탁드려요~ noun 프로젝트 관련해서 추가해야할 내용도 넣어주세요~ @soohyunpae 

https://docs.google.com/presentation/d/1gzpFZWlUWvj9Zm33PcYsj6sLmC2Q8SgZmcJY7zLL_DE/edit?usp=sharing

2015년 5월 12일 오후 3:02, jenniferkang notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
@nanshil 난실님~ 영문 작업 중인데요, 괜찮으시면 영문 초안 한번 HQ 에 공유해서 피드백 받아도 될까요? 오늘 공유하고 다음주 화요일 정도까지 피드백 받으면 일정에는 문제 없을 것 같은데...어떠세요?

**Comment by soohyunpae** [comment]
영문 텍스트 초안 오늘 밤 완료 후 공유 예정입니다. 
HQ에서 크리티컬한 피드백 있으면 최종 오픈 전에 한번 반영 요청드릴게요.

**Comment by soohyunpae** [comment]
@nanshil @mozodev 영문 초안입니다.
https://docs.google.com/presentation/d/1nPlWd_wpettVAlSVyelC--d9kaky3d4aQsQctQ-b2cg/edit?usp=sharing
메인 텍스트는 HQ 팀에 공유했구요, 목요일까지 피드백 받기로 했습니다.

**Comment by nanshil** [comment]
네~ 확인해볼께요!

2015-06-03 0:59 GMT+09:00 Soohyun Pae notifications@github.com:

**Comment by mozodev** [comment]
@khseo 

서밋 페이지
https://summit.creativecommons.org/kr/ 

작업 중인 임시 로고 공모 페이지
http://f15bedb5.ngrok.io

**Comment by soohyunpae** [comment]
@mozodev 
영문 페이지 텍스트입니다.
https://docs.google.com/presentation/d/1nPlWd_wpettVAlSVyelC--d9kaky3d4aQsQctQ-b2cg/edit#slide=id.g9fa8454d9_0_123

일단 이 상태로 작업 부탁드려요. Matt 한테 그 링크로 먼저 도메인 관련 얘기해놓은 다음에 추가로 수정 작업하면 될 것 같아요.

@nanshil 님 라이선스/저작권 귀속 문구 관련해서 HQ리걸팀(Diane)한테 다시 확인 부탁해놨어요. 그 내용에 따라 최종 문구 수정할게요~

**Comment by soohyunpae** [comment]
HQ에 문구 확인 다시 한번 했어요. 당선작의 권리만 CC에 귀속되고, 나머지는 지원자는 그대로 권리를 갖는 것으로 하면 되어서 동의서 문구 그렇게 작성했어요. '당선되면 작품에 대한 권리는 CC에 양도한다'로요. 

@mozodev 님 보셨겠지만 어제 저녁에 Matt 한테 일정 언급해놓았어요. 바로 처리해주길 바라며...;

**Comment by mozodev** [comment]
@creativecommonskorea/2015-summit 
http://logo.cckorea.org
Open for beta service!

**Comment by soohyunpae** [comment]
@mozodev 님 계정 생성하려고 했는데 비밀번호 입력란이 없어서 등록이 안되네요~
메인 페이지만 확인하고 
https://docs.google.com/presentation/d/1nPlWd_wpettVAlSVyelC--d9kaky3d4aQsQctQ-b2cg/edit#slide=id.g9fa8454d9_0_242
여기에 영문 수정사항 코멘트로 달고 빨간색으로 표시했어요~

**Comment by nanshil** [comment]
[개발관련] 
@mozodev 님~

윈도우 언어에 따라 국문/영문 자동으로 설정되었다고 했는데.. 그럼 자동 번역이에요? 아니면 국문, 영문 사이트가 각각 있어서 해당 언어로 보여주는 거에요? 자동 번역이면 영문을 디폴트로 해서 번역해줘야 할것 같고, 각각 언어이면 한국어를 최근 내용으로 업데이트 해야할것 같은데..@soohyunpae님! 영문 최종 토대로 국문 텍스트 정리 부탁드려도 될까요?

**Comment by nanshil** [comment]
[개발관련] 
@mozodev 님~

회원가입화면에서 가입 완료되었다는 멘트 없이 바로 메인 화면으로 이동해버리네요..
가입 완료가 되었는지 확인이 안되요! 완료 처리되면 알럿창이나 완료 확인 페이지 뜰 수 있두록 해주세요!
- 가입이 안되어서 업로드 확인이 안되네요~ 이건 가입완료되면 확인해볼께요!

**Comment by soohyunpae** [comment]
@nanshil 네 지금 국문본에 작업 중이에요~ 끝나면 다시 알려드릴게요~

**Comment by nanshil** [comment]
@mozodev ~~
멤버에서 자꾸 경희님이 안보여요~~ 확인 부탁드려요~~

경희님!

디자인 관련하여..
- 메인 화면 상단에 글로벌 써밋 안내 페이지로 이동하는 버튼이 하나 있어야 할것 같아요!
- 하단에 CC 또는 CCKOREA 관련하여 컨텍포인트 정보가 있는 풋터가 있어야 할것 같아요!
  (-> 이건 제가 전화로 설명 드릴께요!)
- 지금 로그인 정보 들어가면 하단에 회원가입이 그냥 영문으로 나오는데..
  참여하는 모든 사람이 회원가입을 가장 먼저 해야하는 상황이어서 여기도 버튼으로 눈에 띄게 해줘야 할것 같아요~

확인 부탁드릴께요~~~

2015-06-05 10:47 GMT+09:00 Yeongtaek Hong notifications@github.com:

**Comment by soohyunpae** [comment]
국문본에 수정사항 빨간색으로 표시했습니다~ @nanshil님 한번 확인 부탁드려요~
번역은 자동 번역은 아닌 거 같아요. 제가 지금 영문 국문 OS 둘다 켜놓고 보고 있는데 둘다 우리가 넣은 텍스트대로 나오네요~

**Comment by soohyunpae** [comment]
@khseo 님 여기요~ 저 위에 @nanshil 님 코멘트 봐주세요 ㅎ

**Comment by nanshil** [comment]
앗~ @soohyunpae 감사합니당! ㅎㅎ 국문텍스트는 확인해볼께요~~~(밥좀 먹고요...)

**Comment by mozodev** [comment]
지금 웹사이트 로그를 보니까 세 분 모두 계정을 만드셨는데 로그인에 실패하고 있는데요... 제가 보안 때문에 이메일 인증을 걸어놓은 상태에서 현재 이메일이 발송이 안되니까 로그인 못하시는거 거든요... 일단 이메일 인증을 풀었고 세 분 계정을 모두 제가 삭제했으니까 다시 테스트해보시면 됩니다. 

그리고 경희님 소환(ㅎㅎ) 관련해서는 @ ks 이렇게 치면 자동 완성되서 나오는데요. 오호 이렇게 하니까 웬 남자가 소환되는군요 ㅋㅋㅋ

**Comment by mozodev** [comment]
이슈가 계속 나올거 같아서 정확하게 하기 위해서 https://github.com/creativecommonskorea/logo-summit/issues 여기에 입력해주시면 감사하겠습니다. 일단 지금까지 이슈 정리해 놓을께요~ @creativecommonskorea/2015-summit

**Comment by soohyunpae** [comment]
가입-로그인-업로드 성공했어요~

**Comment by mozodev** [comment]
@nanshil 일단 콘텐츠(글, 로고 설명)와 인터페이스 문자열(로그인, 회원 가입 등의 텍스트)이 웹사이트가 다국어를 지원하는 방식은 인터페이스 문자열에 대해 이미 번역되어 있는 문자열을 교체해서 보여주는 겁니다. 하나의 웹사이트에 인터페이스 원고만 해당 언어값에 따라 샥샥 변하는거죠.. 글에 대해서는 사람이 번역하기를 눌러서 영어로 작성한 글을 국문으로 번역할 수 있고 그 반대도 되는데 이런 경우는 거의 벌어지지 않죠... 각자 편한 말로 떠들면 됩니다. 모듈을 추가하면 구글 자동 번역을 할 수도 있습니다만...

**Comment by mozodev** [comment]
참고로 국문
http://logo.cckorea.org/ko
영문
http://logo.cckorea.org/en
이렇게 확인해볼 수 있습니다.

아직 번역 안된 문자열들이 몇 개 있어서 곧 번역 예정입니다.

**Comment by soohyunpae** [comment]
@nanshil @mozodev 

깃허브의 다른 글 연결하는 걸 어떻게 하는지 잘 몰라서... 급한대로 그냥 긁어왔어요.
맷에게 HQ 써밋 사이트에 로고 공모전 연결해달라고 요청했는데요, 다음과 같이 피드백이 왔습니다.

Can we make some changes to that page?

First, let's not ask people to submit a JPEG, when a logo would look awful
in that format. A PNG will be better.
--> 웹사이트에 올리는 용이고, 최종 당선작은 따로 요청할거라고 얘기해주면 될까요? 아님 맷 말대로 png로 받는 게 나을지요?

Second, let's not assume the world uses proprietary software. Let's ask for
submissions in an open format, like SVG.
--> 일리 있는 것 같은데 어떠세요?

Finally, we need to get that page under HTTPS. Happy to talk to whomever we
need to make that happen.
--> 이건 영택님이 직접 말씀해주시는 게 좋을 거 같아요.

**Comment by mozodev** [comment]
저도 이거 어제 봤어요. 투명 png로 받는 건 제가 수정할 수 있고요. 다만 지금은 맷이 말한거 처럼 svg, ai 등의 소스는 안 받고 있거든요. 난실님과 이야기하기로는 일단 png 결과물만 보고 나중에 선정되면 별도로 메일로 커뮤니케이션하면서 소스 파일을 요청해서 받으려고 하는데... 

ssl은 맷 말이 맞아요. 우리나라는 잘 안 쓰는데. 흠 이것도 제가 적용하고 다시 알려드릴게요. 원래 제대로 하려면 서버 인증서를 돈 주고 구매해야 하는데 제 기억으로 종류에 다라 다르지만 일년에 12만원, 30~50만원 정도 계속 갱신해야 돼요. 공짜로 제공해주는 곳이 있어서 적용해볼께요.

**Comment by jenniferkang** [comment]
CC로고 때문에 당선작이 아닌 경우에는 사용할 수 있도록 저작권 푸는게 안되니.
저도 당선작만 ai화일이나 svg화일을 받는게 어떨런지요~

2015년 6월 13일 오후 2:02, Yeongtaek Hong notifications@github.com님이 작성:

**Comment by jenniferkang** [comment]
@soohyunpae  션님~~  
로고 공모전 지금 하고 있는거요. HQ에서도 홍보와 공지가 필요할 것 같아요. 
영문으로 되어 있는 글이 없는 것 같아요. 
- 글로벌 써밋 영문 사이트에 로고 공모전 안내 들어가고 
- creativecommons.org 블로그에도 올라가면 좋을 것 같아요. 
- https://www.facebook.com/creativecommons 여기에서도 홍보해주시면 좋을 것 같아요. 

추신 :  CC affiliates  뉴스 보여주는 메뉴가 이상하게 보이네요. 
http://planet.creativecommons.org

**Comment by soohyunpae** [comment]
네 맷한테 써밋 영문 사이트에 로고 공모전 안내글이랑 링크 넣어달라고 했는데 그거에 대해서 지난번에 피드백이 온거에요~
https://github.com/creativecommons/global-summit-/issues/20
https 관련해서 @mozodev 영택님께 맷이랑 직접 얘기해달라고 부탁드렸는데 완료된 건가요? 아침에 맷이 완료되었다고 깃허브에 올렸길래 저도 좀아까 영문 써밋 사이트 확인해봤는데 공지가 없어서...
영택님 확인 부탁드려요~!

영문 사이트에 오픈되는대로 CC사이트랑 페북에 홍보되도록 얘기할게요.

**Comment by mozodev** [comment]
@soohyunpae  
All set and it's up on the site :) 완료된거죠! 
로고 공모전 사이트 https 및 원고 수정 https://github.com/creativecommonskorea/logo-summit/issues/20 완료되서 닫았습니다.
서밋 영문 사이트는 맷이 원고를 업데이트해야하는데 제 PR만 받고 일단 서버에 적용까지 완료됐어요...
맷이 어떻게 일하는지 모르겠는데 원고도 없고 해서 정확하게 자기 일이라고 생각하지 않는거 같기도 하네요..
걍 제가 원고 추가해서 또 PR 날릴까요?

**Comment by jenniferkang** [comment]
PR이 뭔가요?

앞으로 이렇게 쭈욱.. 이러면 어쩌나...

2015년 6월 18일 오전 11:26, Yeongtaek Hong notifications@github.com님이 작성:

**Comment by mozodev** [comment]
@jenniferkang 

```
Pull Request
기여한 코드를 원 프로젝트로 전송
원 프로젝트 소유자에게 코드를 땡겨 받아 달라고 요청하는 거죠.
```

깃헙이 사용 중인 협업 방식입니다.

예를 들면, 
맷이 HQ 서밋 웹사이트 레포 소유자고 저는 거기에 직접 코드를 기여할 수 없어요. 왜냐면 믿을 수 없는 사람이 믿을 수 없는 코드를 막 저장하고 그러면 난리가 나니까요. 그래서 제가 HQ 레포를 씨씨코리아로 복사를 해 와서 `Fork` 수정하고 그 수정한 코드를 복사해왔던 원본 HQ 레포로 보내는 `Pull Request` 거죠. 맷은 이렇게 누군가 보낸 코드를 검토하고 이상이 없으면 그 코드 기여자와 논의도 하고 수정하고 해서 HQ 레포에 반영을 하고 다시 서버에 가서 그 변경 사항을 적용하면 최종적으로 웹사이트에 반영이 됩니다.

어떤 분은 이렇게 표현하셨네요..
[GitHub로 남의 프로젝트에 감놓고 배놓기](https://dogfeet.github.io/articles/2012/how-to-github.html)

**Comment by soohyunpae** [comment]
@mozodev 영문 사이트 텍스트도 수정해서 PR가능하세요? 그러시면 해주세요~ 보고 수정할 데 있으면 알아서 수정해서 반영해달라고 하면 되지 않을까요?

그리고 제가 영문 써밋 사이트 공지+홍보 관련해서 다른 사람들 추가해서 한꺼번에 얘기해놓을게요.

**Comment by jenniferkang** [comment]
앞으로 홈페이지는 그냥 우리가 해야할 것 같아요. (영문버젼도)
자주 업데이트 되는 부분은 위키와 같은 형태로 수정을 할 수 있도록 한다든지.

앞으로 일을 빨리 진행할 수 있는 방법을 미리 고민해서 HQ에 제한을 해야 할 것 같아요.

일단 영택님이 텍스트까지 수정해서 PR요청해 주세요.

2015년 6월 18일 오전 11:45, Soohyun Pae notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
네 며칠 전에 matt한테 권한(한국어 써밋 사이트) 달라고 요청했었는데 반응이 없었어요.
제시카랑 그 문제에 대해서 논의했었는데요, 일단 제가 matt한테 권한 달라고 요청해보고 또 반응 없으면 ryan 이랑 steering committee 전체에 이슈 제기하겠다고 했었어요.

네 말씀하신대로 일단 국문 사이트 권한 문제랑, 영문 사이트 관리에 대한 명확한 가이드라인/권한 관련 이슈 정리해서 steering committee 전체로 한번 커뮤니케이션 해야할 것 같아요. 앞으로 온라인에 업데이트 되어야 할 내용 정리해보는 것이 좋을지요?

**Comment by mozodev** [comment]
기왕이면 그렇게 좀 계획을 가지고 논의하는게 커뮤니케이션 비용을 줄일 수 있는 좋은 방법일 것 같아요. 
무조건 니네는 느리고 의지가 별로 없어 보이니, 우리가 뭔가 많이 할거니까 권한 줘 이런 식이면 좀 마찰이 많이 생길 것 같고요... 이런 방식보다는 계획을 세우고 각자 잘 할 수 있는 부분에 대해 책임과 권한을 좀 명확히 할 수 있으면 훨씩 좋을 것 같습니다.

일단 서밋 웹사이트와 관련해서 예상되는 부분은...

### 1. 행사 사전 홍보
- 세션, 연사 정보 업데이트
- 참가자, 연사 등록 관리

세션 프로그램 제안받아서 확정되면 정보를 업데이트해서 본격적으로 서밋 홍보를 해야하는데 현재 랜딩 페이지로 계속 갈건지... 아마도 새로운 디자인으로 구축하는게 맞겠죠.. 이건 어느정도 세션이 결정되면 음 근데 2번이 결정되면 바로 구축을 해야겠네요..

### 2. 행사 진행 이후 커뮤니케이션

그리고 예전에 현숙님이 컨퍼런스용 사이트 예를 몇 개 드시면서 이런거 사용해보면 좋겠다고 하셨는데... 예를 들면 실제 행사가 시작되서 세션 진행하면서 즉시 질문이나 의견을 댓글로 달고 세션 평가도 하고 뭐 그런...
어쨌든 이건 HQ하고 합의가 된건지 의사결정이 필요한 문제일 것 같고요...

**Comment by mozodev** [comment]
영문 서밋 페이지 간단히 작업해봤습니다요
http://338a6341.ngrok.io

**Comment by soohyunpae** [comment]
와우~! Register Now  버튼 텍스트도 바꿀 수 있나요? Participate 같은 걸로 바꿔주심 좋을 것 같아요!

**Comment by mozodev** [comment]
수정했고요 더 수정 사항 없으면 바로 PR 날리겠습니다~

**Comment by mozodev** [comment]
https://github.com/creativecommons/global-summit-/pull/32

**Comment by soohyunpae** [comment]
영문 사이트 공지 영택님 pull request 리뷰 및 적용/CC블로그 및 FB 홍보 요청 완료

**Comment by jenniferkang** [comment]
@soohyunpae 로고 공모전이 이제 1주일밖에 남질 않았는데요~ 제대로 된 디자인이 하나도 없어요 ㅠㅠ 
아무래도 홍보를 더 해야할 것 같아요.  홍보해보고 안되면...  기간을 늘려야할 것 같아요. 
수현님 HQ에  추가 홍보 부탁과 일정 기간을 늘리는 부분 고려해야할 것 같고 메일 보내주세요~.

**Comment by soohyunpae** [comment]
네 추가 홍보는 안그래도 어제 얘기해서, 팀이 소셜미디어로 더 홍보하겠다고 했어요.
일정 늘리는 것도 어떨지 얘기해볼게요.
