### ISSUE TITLE
Call for Participation

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#9]
Paul이 금요일까지 HQ 내부 피드백 받은 후 웹사이트에 띄울 예정
Paul한테 우리측 피드백 전달할 것

**Comment by soohyunpae** [comment]
피드백 전달 완료, 일정 확인 중

**Comment by soohyunpae** [comment]
아래 일정으로 진행 예정입니다.

June 4 - call for participation/proposals announced
July 10 - proposal submission deadline
August - session proposers notified of whether proposal is accepted or declined
End of August - summit program is announced
October 14 -17 - global summit

**Comment by jenniferkang** [comment]
@soohyunpae 6/4에 공지하기로 했었네요... 오늘은 6/18일.. ㅠㅠ 
한국어 버젼으로도 올리는게 좋을 것 같아요. 한국어 버젼 만들어주시면 감사요. 대신 한국어 버젼에는 영어로 발표할지 한국어로 발표할지.. 둘다 가능한지.. 체크 항목이 있으면 좋을 것 같아요.

**Comment by soohyunpae** [comment]
네 방금 테스트 페이지 리뷰 끝내고 맷 재촉하고 있어요...오늘 밤엔 나갈 거에요.(제발ㅠ)

한국어 버전 오늘 초안 만들어서 공유해드릴게요. 이번 주 안으로 한국어 버전도 내보내는 걸 목표로~

**Comment by jenniferkang** [comment]
네 한국어 버젼이라도 먼저 공지해요.

2015년 6월 18일 오전 11:14, Soohyun Pae notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
보셨겠지만 영문 버전 어제 새벽에 나갔네요.
https://summit.creativecommons.org/cfp/

한국어 버전 아래 확인/수정 부탁드려요~
https://docs.google.com/forms/d/1TBMRZXKKyuqiwTyS8T40VmlMzAEI4Tw-lSdB9wiZoiQ/edit?usp=sharing

영문 사이트는 맷이 구글 문서가 싫다고 해서 양식을 따로 만들었는데, 우리는 구글 문서로 해도 괜찮지 않을까 싶은데..어떨까요?
그리고 영문 버전이 있으니 그에 대한 안내도 들어가야할 것 같은데 어떠신지요? 영문 버전으로도 프로포절 받지만, 한국 강연자는 한국어 버전으로 접수해달라고 유도하는 내용이 있으면 좋을 것 같아요.

**Comment by jenniferkang** [comment]
1. 한글 프로포절 의견입니다.

세션의 형식, 유형
(기타에 전시와 같은 특별한 형태인 경우에는 기타에 써달라고 해주세요)

언어는 선택하는걸로
한국어 / 영어 / 한국어 영어 둘다

관련자료… :  이건 뭔지 잘 모르겠어요.

세션태그에 ART가 빠졌는데요. culture로 들어가나요?
컬쳐가 너무 넓은 의미는 아닌가 싶어요. (아트, 미디어)를 추가하면 어떨런지요?
1. 그러네요. 한글에도 소개글 올려야겠네요.
2. 날짜별 주제가 확정되어가는 분위기입니다. 우리가 빨리 정해야할 것 같아요.
   물론 나쁘지 않은데요. 그래도 다시 검토하는 걸로.
3. 구글 문서로 하는거 좋아요.
4. 근데 메인 사진의 의미는 뭐래요....
5. 날짜요. 10월 14일에는 공식 행사가 없어서 15일로 표기했는데요. 어떤게 좋을까요?

2015년 6월 19일 오전 9:52, Soohyun Pae notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
- 한글 프로포절 의견입니다.

세션의 형식, 유형
(기타에 전시와 같은 특별한 형태인 경우에는 기타에 써달라고 해주세요)
--> 완료

언어는 선택하는걸로
한국어 / 영어 / 한국어 영어 둘다
--> 완료

관련자료… :  이건 뭔지 잘 모르겠어요.
--> 발표 때 사용할 슬라이드라던가 미디어 작품이라면 그런 거라던가 그런 걸 말하는 것 같아요. 필수 질문은 아니니 받으면 좋을 것 같아요.
발표 자료 초안이나 참고 자료로 바꿀까요?

세션태그에 ART가 빠졌는데요. culture로 들어가나요?
컬쳐가 너무 넓은 의미는 아닌가 싶어요. (아트, 미디어)를 추가하면 어떨런지요?
--> 완료
- 그러네요. 한글에도 소개글 올려야겠네요.
- 날짜별 주제가 확정되어가는 분위기입니다. 우리가 빨리 정해야할 것 같아요.
  물론 나쁘지 않은데요. 그래도 다시 검토하는 걸로.
  --> 그럼 일단 주제를 뺄까요? 한글 버전에서라도.
- 구글 문서로 하는거 좋아요.
  --> 넵~
- 근데 메인 사진의 의미는 뭐래요....
  --> 복 받으시라고...몰라요 폴이 심혈을 기울여 골랐네요.ㅎ
- 날짜요. 10월 14일에는 공식 행사가 없어서 15일로 표기했는데요. 어떤게 좋을까요?
  --> 네 저도 그래서 날짜 바꿔야하지 않냐고 얘기하긴 했었는데, 또 14일에 대해서도 세션 제안을 받을 여지를 두고 있으니까...일단 여기는 열어두어도 괜찮지 않을까요? 사전 행사고 표시는 해두었으니까요.

**Comment by jenniferkang** [comment]
관련자료… : 이건 뭔지 잘 모르겠어요.
--> 발표 때 사용할 슬라이드라던가 미디어 작품이라면 그런 거라던가 그런 걸 말하는 것 같아요. 필수 질문은 아니니 받으면 좋을 것
같아요.
발표 자료 초안이나 참고 자료로 바꿀까요?

=) 네 참고 자료 좋아요.

세션태그에 ART가 빠졌는데요. culture로 들어가나요?
컬쳐가 너무 넓은 의미는 아닌가 싶어요. (아트, 미디어)를 추가하면 어떨런지요?
--> 완료

=) 이거 영문도 마찬가지 아닌가 싶은데. 그쪽에도 우리가 의견 주면 어떨런지요?

**\* 날짜를 모두 10월 14일로 모두 바꾸는걸로~   ( @mozodev  영택님 날짜 바꿔주세요)

2015년 6월 19일 오전 10:28, Soohyun Pae notifications@github.com님이 작성:

**Comment by soohyunpae** [comment]
- 참고자료로 변경했어요.
- 영문 버전에도 태그에 art랑 media 추가 제안할게요.
- 영문 버전에도 날짜 변경 요청해볼게요~
